require("anup.plugins-setup")
require("anup.core.options")
require("anup.core.keymaps")
-- require("anup.core.colorscheme")
require("anup.plugins.tokyonight")
require("anup.plugins.comment")
require("anup.plugins.nvim-tree")
require("anup.plugins.lualine")
require("anup.plugins.telescope")
require("anup.plugins.nvim-cmp")
require("anup.plugins.lsp.mason")
require("anup.plugins.lsp.lspsaga")
require("anup.plugins.lsp.lspconfig")
require("anup.plugins.lsp.null-ls")
require("anup.plugins.autopairs")
require("anup.plugins.treesitter")
require("anup.plugins.gitsigns")
